name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Configure git
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: script
        run: |
          git clone https://github.com/YONG-JAE-LEE/gatsby-blog-starter-with-rescript.git
          git clone -b contents --single-branch https://github.com/dididy/til
          mkdir ./gatsby-blog-starter-with-rescript/posts
          mv ./til/contents ./gatsby-blog-starter-with-rescript/posts/
          cp .env ./gatsby-blog-starter-with-rescript
          cd ./gatsby-blog-starter-with-rescript
          yarn install
          yarn build
        shell: bash

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gatsby-blog-starter-with-rescript/public
